import '../models/entity_model.dart';
import '../models/review_model.dart';

// This contains REAL data from your PostgreSQL database
class RealDatabaseMock {
  static List<Entity> getRealEntities() {
    return [
      Entity(
        entityId: 34,
        name: 'University of Dhaka',
        description: 'প্রাচীনতম এবং বাংলাদেশের সবচেয়ে প্রতিষ্ঠিত বিশ্ববিদ্যালয়। ১৯২১ সালে প্রতিষ্ঠিত।',
        averageRating: 4.25,
        reviewCount: 2,
        avatar: 'https://images.unsplash.com/photo-1523050854058-8df90110c9d1?q=80&w=400',
        categoryName: 'University',
        rootCategoryName: 'Places & Venues',
        rootCategoryId: 2,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'University',
        finalCategoryId: 15,
        finalCategoryIcon: '🎓',
      ),
      Entity(
        entityId: 35,
        name: 'BUET',
        description: 'Bangladesh University of Engineering and Technology - দেশের শীর্ষস্থানীয় প্রকৌশল বিশ্ববিদ্যালয়',
        averageRating: 4.5,
        reviewCount: 1,
        avatar: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=400',
        categoryName: 'University',
        rootCategoryName: 'Places & Venues',
        rootCategoryId: 2,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'University',
        finalCategoryId: 15,
        finalCategoryIcon: '🎓',
      ),
      Entity(
        entityId: 36,
        name: 'North South University',
        description: 'বেসরকারি বিশ্ববিদ্যালয় যা উচ্চমানের শিক্ষার জন্য পরিচিত। ১৯৯২ সালে প্রতিষ্ঠিত।',
        averageRating: 4.2,
        reviewCount: 1,
        avatar: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?q=80&w=400',
        categoryName: 'University',
        rootCategoryName: 'Places & Venues',
        rootCategoryId: 2,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'University',
        finalCategoryId: 15,
        finalCategoryIcon: '🎓',
      ),
      Entity(
        entityId: 37,
        name: 'BRAC University',
        description: 'আন্তর্জাতিক মানসম্পন্ন বেসরকারি বিশ্ববিদ্যালয়। গবেষণা এবং উদ্ভাবনে এগিয়ে।',
        averageRating: 0.0,
        reviewCount: 0,
        avatar: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?q=80&w=400',
        categoryName: 'University',
        rootCategoryName: 'Places & Venues',
        rootCategoryId: 2,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'University',
        finalCategoryId: 15,
        finalCategoryIcon: '🎓',
      ),
      Entity(
        entityId: 38,
        name: 'Grameenphone',
        description: 'বাংলাদেশের বৃহত্তম মোবাইল অপারেটর। গ্রামীণ ব্যাংকের সহযোগিতায় প্রতিষ্ঠিত।',
        averageRating: 3.8,
        reviewCount: 1,
        avatar: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400',
        categoryName: 'Company',
        rootCategoryName: 'Companies & Organizations',
        rootCategoryId: 3,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'Telecommunications Company',
        finalCategoryId: 25,
        finalCategoryIcon: '📱',
      ),
      Entity(
        entityId: 39,
        name: 'Robi Axiata Limited',
        description: 'বাংলাদেশের দ্বিতীয় বৃহত্তম মোবাইল অপারেটর। মালয়েশিয়ার Axiata এর অংশীদারিত্বে।',
        averageRating: 0.0,
        reviewCount: 0,
        avatar: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=400',
        categoryName: 'Company',
        rootCategoryName: 'Companies & Organizations',
        rootCategoryId: 3,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'Telecommunications Company',
        finalCategoryId: 25,
        finalCategoryIcon: '📱',
      ),
      Entity(
        entityId: 40,
        name: 'Square Pharmaceuticals',
        description: 'বাংলাদেশের শীর্ষ ওষুধ কোম্পানি। ১৯৫৮ সাল থেকে সেবা প্রদান করছে।',
        averageRating: 0.0,
        reviewCount: 0,
        avatar: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?q=80&w=400',
        categoryName: 'Company',
        rootCategoryName: 'Companies & Organizations',
        rootCategoryId: 3,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'Pharmaceutical Company',
        finalCategoryId: 28,
        finalCategoryIcon: '💊',
      ),
      Entity(
        entityId: 41,
        name: 'ACI Limited',
        description: 'বহুজাতিক কোম্পানি। ওষুধ, কৃষি এবং ভোগ্যপণ্যে নেতৃত্ব প্রদান করছে।',
        averageRating: 0.0,
        reviewCount: 0,
        avatar: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=400',
        categoryName: 'Company',
        rootCategoryName: 'Companies & Organizations',
        rootCategoryId: 3,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'Conglomerate',
        finalCategoryId: 30,
        finalCategoryIcon: '🏭',
      ),
      Entity(
        entityId: 42,
        name: 'Kasturi Restaurant',
        description: 'ঢাকার অন্যতম জনপ্রিয় রেস্তোরাঁ। ঐতিহ্যবাহী বাংলা খাবারের জন্য বিখ্যাত।',
        averageRating: 4.2,
        reviewCount: 1,
        avatar: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?q=80&w=400',
        categoryName: 'Restaurant',
        rootCategoryName: 'Places & Venues',
        rootCategoryId: 2,
        rootCategoryIcon: '🏢',
        finalCategoryName: 'Restaurant',
        finalCategoryId: 18,
        finalCategoryIcon: '🍽️',
      ),
      Entity(
        entityId: 49,
        name: 'Daraz Bangladesh',
        description: 'বাংলাদেশের শীর্ষ ই-কমার্স প্ল্যাটফর্ম। Alibaba Group এর অংশ।',
        averageRating: 0.0,
        reviewCount: 0,
        avatar: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400',
        categoryName: 'E-commerce',
        rootCategoryName: 'Products & Services',
        rootCategoryId: 4,
        rootCategoryIcon: '🛍️',
        finalCategoryName: 'E-commerce Platform',
        finalCategoryId: 40,
        finalCategoryIcon: '🛒',
      ),
    ];
  }

  static List<Review> getRealReviews() {
    return [
      // Public Reviews
      Review(
        reviewId: 1,
        title: 'Excellent University with Outstanding Facilities',
        content: 'Great education quality and campus facilities. The library is well-equipped with modern resources and the faculty members are highly qualified. Campus life is vibrant with various cultural and sports activities.',
        rating: 4.5,
        userId: 1,
        username: 'StudentReviewer',
        userAvatar: 'https://ui-avatars.com/api/?name=Student+Reviewer&background=7C3AED&color=ffffff',
        entityId: 34,
        entityName: 'University of Dhaka',
        entityAvatar: 'https://images.unsplash.com/photo-1523050854058-8df90110c9d1?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        entityReviewCount: 2,
        entityAverageRating: 4.25,
        likesCount: 45,
        commentsCount: 12,
        viewCount: 523,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),

      // Group Review
      Review(
        reviewId: 2,
        title: 'Best Engineering University in Bangladesh',
        content: 'Top quality engineering education. The curriculum is rigorous and industry-aligned. Labs are well-equipped and professors are experts in their fields.',
        rating: 5.0,
        userId: 2,
        username: 'EngineeringStudent',
        userAvatar: 'https://ui-avatars.com/api/?name=Engineering+Student&background=10B981&color=ffffff',
        entityId: 35,
        entityName: 'BUET',
        entityAvatar: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        entityReviewCount: 1,
        entityAverageRating: 4.5,
        likesCount: 67,
        commentsCount: 18,
        viewCount: 892,
        groupId: 1,
        groupName: 'Tech Enthusiasts Bangladesh',
        groupAvatar: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=400',
        reviewScope: 'group_only',
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
      ),

      Review(
        reviewId: 3,
        title: 'Good Network Coverage Nationwide',
        content: 'Reliable mobile network with good customer service. Data packages are affordable and the network rarely drops in urban areas.',
        rating: 4.0,
        userId: 3,
        username: 'GPCustomer',
        userAvatar: 'https://ui-avatars.com/api/?name=GP+Customer&background=3B82F6&color=ffffff',
        entityId: 38,
        entityName: 'Grameenphone',
        entityAvatar: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400',
        entityRootCategoryName: 'Companies & Organizations',
        entityRootCategoryId: 3,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Telecommunications Company',
        entityFinalCategoryId: 25,
        entityFinalCategoryIcon: '📱',
        entityReviewCount: 1,
        entityAverageRating: 3.8,
        likesCount: 23,
        commentsCount: 5,
        viewCount: 234,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
      ),

      Review(
        reviewId: 4,
        title: 'Amazing Food and Ambiance',
        content: 'Kasturi Restaurant offers authentic Bengali cuisine. The fish curry is exceptional and the service is prompt. Highly recommended for family dining.',
        rating: 4.5,
        userId: 1,
        username: 'FoodLover',
        userAvatar: 'https://ui-avatars.com/api/?name=Food+Lover&background=F59E0B&color=ffffff',
        entityId: 42,
        entityName: 'Kasturi Restaurant',
        entityAvatar: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Restaurant',
        entityFinalCategoryId: 18,
        entityFinalCategoryIcon: '🍽️',
        likesCount: 89,
        commentsCount: 23,
        viewCount: 1245,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
      ),

      // Group Review
      Review(
        reviewId: 5,
        title: 'Great Private University Experience',
        content: 'NSU provides world-class education with modern facilities. International exposure is excellent through exchange programs.',
        rating: 4.3,
        userId: 2,
        username: 'NSUAlumni',
        userAvatar: 'https://ui-avatars.com/api/?name=NSU+Alumni&background=EC4899&color=ffffff',
        entityId: 36,
        entityName: 'North South University',
        entityAvatar: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 34,
        commentsCount: 8,
        viewCount: 456,
        groupId: 2,
        groupName: 'University Students Bangladesh',
        groupAvatar: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=400',
        reviewScope: 'group_only',
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
      ),

      Review(
        reviewId: 6,
        title: 'Historic Campus with Rich Heritage',
        content: 'DU campus is beautiful with historic buildings. The academic environment encourages critical thinking and research.',
        rating: 4.0,
        userId: 3,
        username: 'HistoryBuff',
        userAvatar: 'https://ui-avatars.com/api/?name=History+Buff&background=8B5CF6&color=ffffff',
        entityId: 34,
        entityName: 'University of Dhaka',
        entityAvatar: 'https://images.unsplash.com/photo-1523050854058-8df90110c9d1?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 56,
        commentsCount: 15,
        viewCount: 789,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),

      Review(
        reviewId: 7,
        title: 'Innovative Network Solutions',
        content: 'GP is leading in innovation. Their 4G coverage is excellent and they recently launched 5G in selected areas.',
        rating: 4.2,
        userId: 1,
        username: 'TechEnthusiast',
        userAvatar: 'https://ui-avatars.com/api/?name=Tech+Enthusiast&background=06B6D4&color=ffffff',
        entityId: 38,
        entityName: 'Grameenphone',
        entityAvatar: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400',
        entityRootCategoryName: 'Companies & Organizations',
        entityRootCategoryId: 3,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Telecommunications Company',
        entityFinalCategoryId: 25,
        entityFinalCategoryIcon: '📱',
        likesCount: 41,
        commentsCount: 9,
        viewCount: 567,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
      ),

      // Group Review
      Review(
        reviewId: 8,
        title: 'Perfect Blend of Tradition and Modern Cuisine',
        content: 'The restaurant maintains authenticity while adding modern touches. The hilsa fish preparation is outstanding!',
        rating: 4.8,
        userId: 2,
        username: 'CulinaryExplorer',
        userAvatar: 'https://ui-avatars.com/api/?name=Culinary+Explorer&background=EF4444&color=ffffff',
        entityId: 42,
        entityName: 'Kasturi Restaurant',
        entityAvatar: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Restaurant',
        entityFinalCategoryId: 18,
        entityFinalCategoryIcon: '🍽️',
        likesCount: 102,
        commentsCount: 34,
        viewCount: 1678,
        groupId: 3,
        groupName: 'Dhaka Foodies',
        groupAvatar: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=400',
        reviewScope: 'mixed',
        createdAt: DateTime.now().subtract(const Duration(hours: 18)),
      ),

      Review(
        reviewId: 9,
        title: 'Rigorous Academic Standards',
        content: 'BUET maintains very high standards. The admission process is competitive and the education is top-notch.',
        rating: 4.7,
        userId: 3,
        username: 'FutureEngineer',
        userAvatar: 'https://ui-avatars.com/api/?name=Future+Engineer&background=14B8A6&color=ffffff',
        entityId: 35,
        entityName: 'BUET',
        entityAvatar: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 78,
        commentsCount: 21,
        viewCount: 934,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
      ),

      Review(
        reviewId: 10,
        title: 'Customer Support Needs Improvement',
        content: 'While network quality is good, customer support response time could be better. Waited 30 minutes on hotline.',
        rating: 3.5,
        userId: 1,
        username: 'ConcernedUser',
        userAvatar: 'https://ui-avatars.com/api/?name=Concerned+User&background=F97316&color=ffffff',
        entityId: 38,
        entityName: 'Grameenphone',
        entityAvatar: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400',
        entityRootCategoryName: 'Companies & Organizations',
        entityRootCategoryId: 3,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Telecommunications Company',
        entityFinalCategoryId: 25,
        entityFinalCategoryIcon: '📱',
        likesCount: 15,
        commentsCount: 7,
        viewCount: 289,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
      ),

      // Additional reviews for pagination testing
      Review(
        reviewId: 11,
        title: 'Modern Infrastructure and Labs',
        content: 'NSU campus has state-of-the-art labs and comfortable classrooms. WiFi coverage is excellent throughout campus.',
        rating: 4.4,
        userId: 2,
        username: 'TechStudent',
        userAvatar: 'https://ui-avatars.com/api/?name=Tech+Student&background=A855F7&color=ffffff',
        entityId: 36,
        entityName: 'North South University',
        entityAvatar: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 42,
        commentsCount: 11,
        viewCount: 623,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
      ),

      Review(
        reviewId: 12,
        title: 'Affordable Dining with Great Taste',
        content: 'The pricing is reasonable and the portion sizes are generous. Family-friendly environment.',
        rating: 4.3,
        userId: 3,
        username: 'BudgetDiner',
        userAvatar: 'https://ui-avatars.com/api/?name=Budget+Diner&background=84CC16&color=ffffff',
        entityId: 42,
        entityName: 'Kasturi Restaurant',
        entityAvatar: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Restaurant',
        entityFinalCategoryId: 18,
        entityFinalCategoryIcon: '🍽️',
        likesCount: 67,
        commentsCount: 19,
        viewCount: 1123,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 11)),
      ),

      // Group Review
      Review(
        reviewId: 13,
        title: 'Research Opportunities Abound',
        content: 'DU offers excellent research facilities. Many professors are internationally recognized in their fields.',
        rating: 4.6,
        userId: 1,
        username: 'ResearchScholar',
        userAvatar: 'https://ui-avatars.com/api/?name=Research+Scholar&background=3B82F6&color=ffffff',
        entityId: 34,
        entityName: 'University of Dhaka',
        entityAvatar: 'https://images.unsplash.com/photo-1523050854058-8df90110c9d1?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 91,
        commentsCount: 27,
        viewCount: 1456,
        groupId: 2,
        groupName: 'University Students Bangladesh',
        groupAvatar: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=400',
        reviewScope: 'mixed',
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      ),

      Review(
        reviewId: 14,
        title: 'Fast Internet Speeds',
        content: 'GP internet is fast and reliable. Streaming and gaming work smoothly without interruptions.',
        rating: 4.4,
        userId: 2,
        username: 'StreamingFan',
        userAvatar: 'https://ui-avatars.com/api/?name=Streaming+Fan&background=EC4899&color=ffffff',
        entityId: 38,
        entityName: 'Grameenphone',
        entityAvatar: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400',
        entityRootCategoryName: 'Companies & Organizations',
        entityRootCategoryId: 3,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Telecommunications Company',
        entityFinalCategoryId: 25,
        entityFinalCategoryIcon: '📱',
        likesCount: 53,
        commentsCount: 14,
        viewCount: 745,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
      ),

      Review(
        reviewId: 15,
        title: 'World-Class Engineering Education',
        content: 'BUET graduates are highly sought after. The curriculum prepares you well for industry challenges.',
        rating: 4.9,
        userId: 3,
        username: 'IndustryProfessional',
        userAvatar: 'https://ui-avatars.com/api/?name=Industry+Pro&background=10B981&color=ffffff',
        entityId: 35,
        entityName: 'BUET',
        entityAvatar: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 134,
        commentsCount: 42,
        viewCount: 2134,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 13)),
      ),

      Review(
        reviewId: 16,
        title: 'Authentic Bengali Flavors',
        content: 'Kasturi serves the most authentic Bengali food I have ever tasted outside my home. The mustard fish is a must-try!',
        rating: 5.0,
        userId: 1,
        username: 'BengaliCuisineExpert',
        userAvatar: 'https://ui-avatars.com/api/?name=Bengali+Expert&background=F59E0B&color=ffffff',
        entityId: 42,
        entityName: 'Kasturi Restaurant',
        entityAvatar: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Restaurant',
        entityFinalCategoryId: 18,
        entityFinalCategoryIcon: '🍽️',
        likesCount: 156,
        commentsCount: 48,
        viewCount: 2456,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 14)),
      ),

      // Group Review
      Review(
        reviewId: 17,
        title: 'Excellent Career Placement Support',
        content: 'NSU career center is very active. Many multinational companies visit campus for recruitment.',
        rating: 4.5,
        userId: 2,
        username: 'JobSeeker2024',
        userAvatar: 'https://ui-avatars.com/api/?name=Job+Seeker&background=8B5CF6&color=ffffff',
        entityId: 36,
        entityName: 'North South University',
        entityAvatar: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 73,
        commentsCount: 20,
        viewCount: 987,
        groupId: 1,
        groupName: 'Tech Enthusiasts Bangladesh',
        groupAvatar: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=400',
        reviewScope: 'group_only',
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
      ),

      Review(
        reviewId: 18,
        title: 'Reliable Network Even in Rural Areas',
        content: 'GP coverage extends to most rural areas which is impressive. Great for staying connected during travels.',
        rating: 4.1,
        userId: 3,
        username: 'FrequentTraveler',
        userAvatar: 'https://ui-avatars.com/api/?name=Traveler&background=06B6D4&color=ffffff',
        entityId: 38,
        entityName: 'Grameenphone',
        entityAvatar: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=400',
        entityRootCategoryName: 'Companies & Organizations',
        entityRootCategoryId: 3,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'Telecommunications Company',
        entityFinalCategoryId: 25,
        entityFinalCategoryIcon: '📱',
        likesCount: 38,
        commentsCount: 10,
        viewCount: 534,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 16)),
      ),

      Review(
        reviewId: 19,
        title: 'Culturally Rich Campus Life',
        content: 'DU has a vibrant cultural scene. Regular events, debates, and festivals make campus life memorable.',
        rating: 4.7,
        userId: 1,
        username: 'CultureVulture',
        userAvatar: 'https://ui-avatars.com/api/?name=Culture+Buff&background=EF4444&color=ffffff',
        entityId: 34,
        entityName: 'University of Dhaka',
        entityAvatar: 'https://images.unsplash.com/photo-1523050854058-8df90110c9d1?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 95,
        commentsCount: 31,
        viewCount: 1567,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 17)),
      ),

      Review(
        reviewId: 20,
        title: 'Top Faculty Members',
        content: 'BUET professors are not just teachers but mentors. Their industry experience adds immense value to learning.',
        rating: 4.8,
        userId: 2,
        username: 'GratefulStudent',
        userAvatar: 'https://ui-avatars.com/api/?name=Grateful+Student&background=14B8A6&color=ffffff',
        entityId: 35,
        entityName: 'BUET',
        entityAvatar: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=400',
        entityRootCategoryName: 'Places & Venues',
        entityRootCategoryId: 2,
        entityRootCategoryIcon: '🏢',
        entityFinalCategoryName: 'University',
        entityFinalCategoryId: 15,
        entityFinalCategoryIcon: '🎓',
        likesCount: 112,
        commentsCount: 36,
        viewCount: 1823,
        reviewScope: 'public',
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
      ),
    ];
  }
}
